Vagrant.configure("2") do |config|
  config.ssh.insert_key = false  
  NodeCount = 1
   (1..NodeCount).each do |i|
	 config.vm.define "hashicorp_bionic64#{i}" do |node|			
			setup(node, "#{i}")
		end
	end
   
  #config.vm.provision "shell", path: "install.sh" 
  config.vm.synced_folder ".", "/vagrant",mount_options: ["dmode=775,fmode=664"]
end

def setup(r1, index)
	
	r1.vm.box = "hashicorp/bionic64"	
	r1.vm.network "private_network", ip: "192.168.13.1" + index
	#r1.vm.hostname = "raven" + index + ".mooo.com"
	r1.vm.provider "virtualbox" do |vb| 
		vb.name = "hashicorp_bionic64"+index;
		vb.memory = "1024"
	end
end

