
Vagrant.configure("2") do |config|

  config.vm.box = "windows_2012"  


  config.vm.network "private_network", ip: "192.168.22.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder "D:/aaa_development", "C:/aaa_development"
  config.vm.synced_folder "F:/software", "C:/software"
  config.vm.synced_folder ".", "c:/vagrant"


   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     #vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "4096"	
	vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional'] 
	#add cd drive
	#vb.customize ["storageattach", :id, "--storagectl", "IDE Controller","--port", "0", "--device", "1", "--type", "dvddrive", "--medium", "emptydrive"]
   end
  
  config.vm.provision "shell", path: "install.ps1" 

# trigger reload (reboot)
 
  config.vm.provision :reload

# execute code after reload  
  config.vm.provision "shell", path: "install.ps1", args: [ "2" ]
  
end
