
Vagrant.configure("2") do |config|
 
  config.vm.box = "fasmat/ubuntu1804-desktop"

  
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
     # Customize the amount of memory on the VM:
     vb.memory = "2048"	
	vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional'] 
   end
  

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
  
   SHELL
end
